spring.application.name=springboot-rest
spring.datasource.username=root
spring.datasource.password=techno
spring.datasource.url=jdbc:mysql://localhost/flm
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
server.port=9191
server.servlet.context-path=/product
logging.level.com.flm=DEBUG
